# Generated by Django 3.1.2 on 2020-10-21 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gdsc_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='e2k',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('e2k_file', models.FileField(upload_to='uploads/')),
            ],
        ),
        migrations.AlterField(
            model_name='documents',
            name='document',
            field=models.FileField(upload_to='uploads/'),
        ),
    ]
